apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "okeingress.sanchezapps.net"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: users-service
                port:
                  number: 80