apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tasks-service
  template:
    metadata:
      labels:
        app: tasks-service
    spec:
      containers:
        - name: tasks-service
          image: spring/tasks-service:latest
          ports:
            - containerPort: 80