server:
  port: 7000

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: net.sanchezapps.tasksservice
  pathsToMatch: /**

api:

  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...

spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@test_high?TNS_ADMIN=C:/Java/Spring/micro-services/java-oracle-chatbot/chatbot/ATP_Wallet
    username: TASKS_DB
    password: VUeXKEsXEnr8cZW
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
