server:
  port: 7000

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: net.sanchezapps.tasksservice
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...

spring:
  application:
    name: tasks-service

#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@db_high?TNS_ADMIN=Wallet_db
#    username: TASKS_DB
#    password: 0zjPF83YwFx8Ge7
#  jpa:
#    database: ORACLE
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:sqlserver://chatbotserverdb.database.windows.net:1433;database=chatbotdb;user=casvi@chatbotserverdb;password=Developer09+;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  profiles:
    active: docker
server:
  port: 80