version: '2.1'
services:
  task:
    build: tasks-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8000:8080"
  user:
    build: users-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8001:8080"